export const questionData = [
  {
    Question: "What's a phrase you might hear during finals week?",
    Answer: [
      { text: "I need more coffee!", points: 10 },
      { text: "I’m so stressed!", points: 9 },
      { text: "I’m pulling an all-nighter.", points: 8 },
      { text: "I can't wait for break!", points: 7 },
      { text: "I just want to pass", points: 6 },
      { text: "I hope I can remember everything!", points: 5 },
      { text: "I can't wait for this to be over!", points: 4 },
      { text: "Let’s form a study together!", points: 3 },
    ],
  },
  {
    Question: "Food items that dorm students often stock up",
    Answer: [
      { text: "Instant Noodle", points: 10 },
      { text: "Cereal or granola", points: 9 },
      { text: "Peanut butter", points: 8 },
      { text: "Bread", points: 7 },
      { text: "SPAM", points: 6 },
      { text: "Chips", points: 5 },
      { text: "Dairy products (milk/yoghurt)", points: 4 },
      { text: "Eggs", points: 3 },
    ],
  },
  {
    Question: "Name something a student might do during class",
    Answer: [
      { text: "Daydream", points: 10 },
      { text: "Sleeping", points: 9 },
      { text: "Take Notes", points: 8 },
      { text: "Work on Assignments", points: 7 },
      { text: "Scroll on social media apps", points: 6 },
      { text: "Study for Another Class", points: 5 },
      { text: "Eat Food", points: 4 },
      { text: "Play Games", points: 3 },
    ],
  },
  {
    Question: "Name a way people use to try to fall asleep faster",
    Answer: [
      { text: "counting sheep", points: 10 },
      { text: "listening to music", points: 9 },
      { text: "taking a warm bath/shower", points: 8 },
      { text: "meditating/deep breathing exercises", points: 7 },
      { text: "using a sleep mask", points: 6 },
      { text: "watching TV/youtube", points: 5 },
      { text: "exercise", points: 4 },
      { text: "taking melatonin supplements", points: 3 },
    ],
  },
  {
    Question: "Name a reason people go to the doctor.",
    Answer: [
      { text: "Illness", points: 10 },
      { text: "check up", points: 9 },
      { text: "injury", points: 8 },
      { text: "vaccination", points: 7 },
      { text: "prescription refill", points: 6 },
      { text: "specialist referral", points: 5 },
      { text: "pregnancy", points: 4 },
      { text: "allergies", points: 3 },
    ],
  },
  {
    Question: "Most most liked ice cream flavors",
    Answer: [
      { text: "Vanilla", points: 10 },
      { text: "Chocolate", points: 9 },
      { text: "Strawberry", points: 8 },
      { text: "Mint choco chip", points: 7 },
      { text: "Cookies n cream", points: 6 },
      { text: "Rocky road", points: 5 },
      { text: "Butter pecan", points: 4 },
      { text: "Neapolitan", points: 3 },
    ],
  },
  {
    Question: "What decreases a person's aura?",
    Answer: [
      { text: "Farting in public", points: 10 },
      { text: "Getting Ignored", points: 9 },
      { text: "Unzipped pants", points: 8 },
      { text: "Falling in Public", points: 7 },
      { text: "Voice Crack", points: 6 },
      { text: "Answered Incorrectly", points: 5 },
      { text: "Bad Breath", points: 4 },
      { text: "Accidentally dropped an item", points: 3 },
    ],
  },
  {
    Question: "Something you did, that you don't want your parents to know",
    Answer: [
      { text: "Smoking", points: 10 },
      { text: "Clubbing", points: 9 },
      { text: "Getting drunk", points: 8 },
      { text: "Killing someone", points: 7 },
      { text: "Involved in a fight", points: 6 },
      { text: "Getting someone pregnant", points: 5 },
      { text: "Getting arrested", points: 4 },
      { text: "Using drugs", points: 3 },
    ],
  },
  {
    Question: "What is the hottest accent?",
    Answer: [
      { text: "French", points: 10 },
      { text: "Italian", points: 9 },
      { text: "British", points: 8 },
      { text: "American", points: 7 },
      { text: "Spanish", points: 6 },
      { text: "Scottish", points: 5 },
      { text: "Australian", points: 4 },
      { text: "Hong Kong", points: 3 },
    ],
  },
  {
    Question: "What do people usually do past 12pm?",
    Answer: [
      { text: "Sleeping", points: 10 },
      { text: "Working", points: 9 },
      { text: "Eating", points: 8 },
      { text: "Cooking", points: 7 },
      { text: "Clubbing", points: 6 },
      { text: "Playing games", points: 5 },
      { text: "Studying", points: 4 },
      { text: "Making out", points: 3 },
    ],
  },
];
