export const additionalQuestions = [
  {
    Question:
      "Fruits or vegetables that have other purposes other than as a food",
    Answer: [
      { text: "Cucumber", points: 10 },
      { text: "Eggplant", points: 9 },
      { text: "Carrot", points: 8 },
      { text: "Lemon", points: 7 },
      { text: "Oranges", points: 6 },
      { text: "Banana", points: 5 },
      { text: "Peach", points: 4 },
      { text: "Mango", points: 3 },
    ],
  },
  {
    Question: "Name something that might be a day old",
    Answer: [
      { text: "Food", points: 10 },
      { text: "Baby", points: 9 },
      { text: "Animal", points: 8 },
      { text: "Insect", points: 7 },
      { text: "Flower", points: 6 },
    ],
  },
  {
    Question: "Name a profession that involves getting wet",
    Answer: [
      { text: "Diver", points: 10 },
      { text: "Swimmer", points: 9 },
      { text: "Lifeguard", points: 8 },
      { text: "Firefighter", points: 7 },
      { text: "Plumber", points: 6 },
    ],
  },
  {
    Question: "Name something associated with vampires",
    Answer: [
      { text: "Twilight", points: 10 },
      { text: "Blood", points: 9 },
      { text: "Garlic", points: 8 },
      { text: "Bat", points: 7 },
      { text: "Cape", points: 6 },
      { text: "Dracula", points: 5 },
      { text: "Fangs", points: 4 },
      { text: "Halloween", points: 3 },
    ],
  },
  {
    Question: "Name something people might only do once a week",
    Answer: [
      { text: "Laundry", points: 10 },
      { text: "Grocery shop", points: 9 },
      { text: "Exercise", points: 8 },
      { text: "Go to church", points: 7 },
      { text: "Cleaning/taking out trash", points: 6 },
      { text: "Watch ongoing series", points: 5 },
    ],
  },
  {
    Question: "What’s the worst place to accidentally fall asleep",
    Answer: [
      { text: "Job Interview", points: 10 },
      { text: "Meeting", points: 9 },
      { text: "In Class", points: 8 },
      { text: "Wedding", points: 7 },
      { text: "In the front row of a comedy show", points: 6 },
      { text: "Toilet", points: 5 },
      { text: "Public Transport", points: 4 },
      { text: "Gym", points: 3 },
    ],
  },
  {
    Question: "What’s a bad reason to call in sick to work?",
    Answer: [
      { text: "Forgot to do Laundry", points: 10 },
      { text: "Still wanting to sleep", points: 9 },
      { text: "Forgot to set alarm", points: 8 },
      { text: "Binge Watching a Show", points: 7 },
      { text: "My favorite sports team lost", points: 6 },
      { text: "Dog ate my shoe", points: 5 },
      { text: "Lost my phone", points: 4 },
      { text: "Getting Deported", points: 3 },
    ],
  },
  {
    Question: "Name something you shouldn’t do while driving",
    Answer: [
      { text: "Texting", points: 10 },
      { text: "Drinking", points: 9 },
      { text: "Eating", points: 8 },
      { text: "Sleeping", points: 7 },
      { text: "Reading", points: 6 },
      { text: "Taking Photos", points: 5 },
      { text: "Arguing with someone", points: 4 },
      { text: "Changing with clothes", points: 3 },
    ],
  },
  {
    Question: "Name something you might do in the middle of the night",
    Answer: [
      { text: "Going to the bathroom", points: 10 },
      { text: "Checking your phone", points: 9 },
      { text: "Try to fall back asleep", points: 8 },
      { text: "Sleep Walking", points: 7 },
      { text: "Cooking Instant Noodles", points: 6 },
      { text: "Adjusting the AC", points: 5 },
      { text: "Drink water", points: 4 },
      { text: "Fix pillow", points: 3 },
    ],
  },
  {
    Question: "Name something you wouldn't want to find on your bed",
    Answer: [
      { text: "Bugs/Animal", points: 10 },
      { text: "Food/crumbs", points: 9 },
      { text: "Dust", points: 8 },
      { text: "Wet spot", points: 7 },
      { text: "Stain", points: 6 },
      { text: "A stranger", points: 5 },
      { text: "Friend(s)", points: 4 },
      { text: "Your in-laws", points: 3 },
    ],
  },
  {
    Question: "What's the most annoying habit a roommate can have",
    Answer: [
      { text: "Being dirty", points: 10 },
      { text: "Snoring", points: 9 },
      { text: "Stealing", points: 8 },
      { text: "Noisy", points: 7 },
      { text: "Untidy", points: 6 },
      { text: "Using your stuff without asking", points: 5 },
      {
        text: "Always forgetting to return the money they owed from you",
        points: 4,
      },
      { text: "Being overly nosy", points: 3 },
    ],
  },
  {
    Question: "Name things that computer science students hardly do",
    Answer: [
      { text: "Getting a job💀", points: 10 },
      { text: "Socialize", points: 9 },
      { text: "Take a shower", points: 8 },
      { text: "Getting a partner", points: 7 },
      { text: "Sleep", points: 6 },
      { text: "Exercise", points: 5 },
      { text: "Debugging/fixing their code", points: 4 },
      { text: "Laundry", points: 3 },
    ],
  },
  {
    Question: "Name things that your roommate do while you're sleeping",
    Answer: [
      { text: "Also sleeping", points: 10 },
      { text: "Studying/doing assignments", points: 9 },
      { text: "Watching films/movies", points: 8 },
      { text: "Playing games", points: 7 },
      { text: "Taking a bath", points: 6 },
      { text: "Eating", points: 5 },
      { text: "Crying", points: 4 },
      { text: "Taking a photo of you", points: 3 },
    ],
  },
  {
    Question: "What’s something people often forget to pack for a trip​",
    Answer: [
      { text: "Underwear", points: 10 },
      { text: "Toothbrush", points: 9 },
      { text: "Phone charger", points: 8 },
      { text: "Medication", points: 7 },
      { text: "Travel documents", points: 6 },
      { text: "Sun screen", points: 5 },
      { text: "Shirt", points: 4 },
      { text: "Sandals", points: 3 },
    ],
  },
  {
    Question: "Name something that starts with the word “chow”",
    Answer: [
      { text: "Chow-Mein", points: 10 },
      { text: "Chowder", points: 9 },
      { text: "Chow Time", points: 8 },
      { text: "Chow Down", points: 7 },
      { text: "Chow Hall", points: 6 },
      { text: "Chow Hound", points: 5 },
      { text: "Chow Chow", points: 4 },
      { text: "Chow Line", points: 3 },
    ],
  },
  {
    Question: "Name things engineering students avoid",
    Answer: [
      { text: "Shower", points: 10 },
      { text: "Grass", points: 9 },
      { text: "Romance", points: 8 },
      { text: "Algebra & Calculus", points: 7 },
      { text: "Job Interviews", points: 6 },
      { text: "Group Projects", points: 5 },
      { text: "Writing Reports / Papers", points: 4 },
      { text: "A healthy sleep schedule", points: 3 },
    ],
  },
  {
    Question: "Fill in the blank: pack of _____",
    Answer: [
      { text: "Wolves", points: 10 },
      { text: "Gum", points: 9 },
      { text: "Cigs/smokes", points: 8 },
      { text: "Cards", points: 7 },
      { text: "Lies", points: 6 },
      { text: "abs", points: 5 },
      { text: "thieves", points: 4 },
      { text: "matches", points: 3 },
    ],
  },
  {
    Question: "Name Top 8 Most Listened Artist on Spotify in February 2025",
    Answer: [
      { text: "Bruno Mars", points: 10 },
      { text: "The Weeknd", points: 9 },
      { text: "Lady Gaga", points: 8 },
      { text: "Billie Eilish", points: 7 },
      { text: "Kendrick Lamar", points: 6 },
      { text: "Bad Bunny", points: 5 },
      { text: "ColdPlay", points: 4 },
      { text: "Rihanna", points: 3 },
    ],
  },
  {
    Question: "Whats the worse thing to say on a first date?",
    Answer: [
      { text: "So youre paying right?", points: 10 },
      { text: "My ex used to love this place", points: 9 },
      { text: "Oh i forgot my wallet", points: 8 },
      { text: "So how many kids do you want", points: 7 },
      { text: "nothing", points: 6 },
      { text: "you look ____ in person", points: 5 },
      {
        text: "My mom didn't want me to come on this date, but she won't be an issue anymore.",
        points: 4,
      },
      { text: "Marry me", points: 3 },
    ],
  },
  {
    Question: "Name a famous Hong Kong actor",
    Answer: [
      { text: "Bruce Lee", points: 10 },
      { text: "Jackie Chan", points: 9 },
      { text: "Chow Yun-Fat", points: 8 },
      { text: "Andy Lau", points: 7 },
      { text: "Jet Li", points: 6 },
      { text: "Leslie Cheung", points: 5 },
      { text: "Tony Leung Chiu-wai", points: 4 },
      { text: "Donnie Yen", points: 3 },
    ],
  },
  {
    Question: "What to do when you have a headache",
    Answer: [
      { text: "Go to the doctor", points: 10 },
      { text: "Go to amusement parks", points: 9 },
      { text: "Call a friend", points: 8 },
      { text: "Go shopping", points: 7 },
      { text: "Go to sleep", points: 6 },
      { text: "Eat medicine", points: 5 },
      { text: "Play games", points: 4 },
      { text: "Reels scrolling", points: 3 },
    ],
  },
  {
    Question: "What NOT to wear during a job interview",
    Answer: [
      { text: "Birthday suit (Nothing)", points: 10 },
      { text: "Shorts", points: 9 },
      { text: "Pajamas", points: 8 },
      { text: "Swimming suit", points: 7 },
      { text: "Torn clothes", points: 6 },
      { text: "hat", points: 5 },
      { text: "Dirty clothes", points: 4 },
      { text: "Flip flops", points: 3 },
    ],
  },
  {
    Question: "What do people usually eat in a buffet",
    Answer: [
      { text: "Bread", points: 10 },
      { text: "Seafood", points: 9 },
      { text: "Noodles", points: 8 },
      { text: "Ice Cream", points: 7 },
      { text: "Meat/Steak", points: 6 },
      { text: "Omelette egg", points: 5 },
      { text: "Cereal", points: 4 },
      { text: "Fruits", points: 3 },
    ],
  },
  {
    Question: "Name something that kids really like",
    Answer: [
      { text: "Toys", points: 10 },
      { text: "Candy", points: 9 },
      { text: "Vacation", points: 8 },
      { text: "Ice Cream", points: 7 },
      { text: "Video games", points: 6 },
      { text: "Running", points: 5 },
      { text: "Gadgets", points: 4 },
      { text: "Watching movies/videos", points: 3 },
    ],
  },
  {
    Question: "Largest cities in the world by population",
    Answer: [
      { text: "Tokyo", points: 10 },
      { text: "Delhi", points: 9 },
      { text: "Shanghai", points: 8 },
      { text: "Dhaka", points: 7 },
      { text: "Sao Paulo", points: 6 },
      { text: "Cairo", points: 5 },
      { text: "Mexico City", points: 4 },
      { text: "Beijing", points: 3 },
    ],
  },
  {
    Question: "Most populated countries",
    Answer: [
      { text: "India", points: 10 },
      { text: "China", points: 9 },
      { text: "Unites States", points: 8 },
      { text: "Indonesia", points: 7 },
      { text: "Pakistan", points: 6 },
      { text: "Nigeria", points: 5 },
      { text: "Brazil", points: 4 },
      { text: "Bangladesh", points: 3 },
    ],
  },
  {
    Question: "Famous Japanese Food",
    Answer: [
      { text: "Sushi", points: 10 },
      { text: "Ramen", points: 9 },
      { text: "Sashimi", points: 8 },
      { text: "Onigiri", points: 7 },
      { text: "Tempura", points: 6 },
      { text: "Takoyaki", points: 5 },
      { text: "Natto", points: 4 },
      { text: "Yakitori", points: 3 },
    ],
  },
  {
    Question: "World's Best Airlines of 2024",
    Answer: [
      { text: "Qatar Aiways", points: 10 },
      { text: "Singapore Airlines", points: 9 },
      { text: "Emirates", points: 8 },
      { text: "All Nippon Airways", points: 7 },
      { text: "Cathay Pacific", points: 6 },
      { text: "Japan Airlines", points: 5 },
      { text: "Turkish Airlines", points: 4 },
      { text: "Eva Air", points: 3 },
    ],
  },
  {
    Question: "Most Popular Pet",
    Answer: [
      { text: "Dog", points: 10 },
      { text: "Cat", points: 9 },
      { text: "Fish", points: 8 },
      { text: "Hamster", points: 7 },
      { text: "Rabbit", points: 6 },
      { text: "Bird", points: 5 },
      { text: "Reptile", points: 4 },
      { text: "Horse", points: 3 },
    ],
  },
];
