export const additionalQuestions = [
  {
    Question:
      "Fruits or vegetables that have other purposes other than as a food",
    Answer: [
      { text: "Cucumber", points: 10 },
      { text: "Eggplant", points: 9 },
      { text: "Carrot", points: 8 },
      { text: "Lemon", points: 7 },
      { text: "Oranges", points: 6 },
      { text: "Banana", points: 5 },
      { text: "Peach", points: 4 },
      { text: "Mango", points: 3 },
    ],
  },
  {
    Question: "Name something that might be a day old",
    Answer: [
      { text: "Food", points: 10 },
      { text: "Baby", points: 9 },
      { text: "Animal", points: 8 },
      { text: "Insect", points: 7 },
      { text: "Flower", points: 6 },
    ],
  },
  {
    Question: "Name a profession that involves getting wet",
    Answer: [
      { text: "Diver", points: 10 },
      { text: "Swimmer", points: 9 },
      { text: "Lifeguard", points: 8 },
      { text: "Firefighter", points: 7 },
      { text: "Plumber", points: 6 },
    ],
  },
  {
    Question: "Name something associated with vampires",
    Answer: [
      { text: "Twilight", points: 10 },
      { text: "Blood", points: 9 },
      { text: "Garlic", points: 8 },
      { text: "Bat", points: 7 },
      { text: "Cape", points: 6 },
      { text: "Dracula", points: 5 },
      { text: "Fangs", points: 4 },
      { text: "Halloween", points: 3 },
    ],
  },
  {
    Question: "Name something people might only do once a week",
    Answer: [
      { text: "Laundry", points: 10 },
      { text: "Grocery shop", points: 9 },
      { text: "Exercise", points: 8 },
      { text: "Go to church", points: 7 },
      { text: "Cleaning/taking out trash", points: 6 },
      { text: "Watch ongoing series", points: 5 },
    ],
  },
  {
    Question: "What’s the worst place to accidentally fall asleep",
    Answer: [
      { text: "Job Interview", points: 10 },
      { text: "Meeting", points: 9 },
      { text: "In Class", points: 8 },
      { text: "Wedding", points: 7 },
      { text: "In the front row of a comedy show", points: 6 },
      { text: "Toilet", points: 5 },
      { text: "Public Transport", points: 4 },
      { text: "Gym", points: 3 },
    ],
  },
  {
    Question: "What’s a bad reason to call in sick to work?",
    Answer: [
      { text: "Forgot to do Laundry", points: 10 },
      { text: "Still wanting to sleep", points: 9 },
      { text: "Forgot to set alarm", points: 8 },
      { text: "Binge Watching a Show", points: 7 },
      { text: "My favorite sports team lost", points: 6 },
      { text: "Dog ate my shoe", points: 5 },
      { text: "Lost my phone", points: 4 },
      { text: "Getting Deported", points: 3 },
    ],
  },
  {
    Question: "Name something you shouldn’t do while driving",
    Answer: [
      { text: "Texting", points: 10 },
      { text: "Drinking", points: 9 },
      { text: "Eating", points: 8 },
      { text: "Sleeping", points: 7 },
      { text: "Reading", points: 6 },
      { text: "Taking Photos", points: 5 },
      { text: "Arguing with someone", points: 4 },
      { text: "Changing with clothes", points: 3 },
    ],
  },
  {
    Question: "Name something you might do in the middle of the night",
    Answer: [
      { text: "Going to the bathroom", points: 10 },
      { text: "Checking your phone", points: 9 },
      { text: "Try to fall back asleep", points: 8 },
      { text: "Sleep Walking", points: 7 },
      { text: "Cooking Instant Noodles", points: 6 },
      { text: "Adjusting the AC", points: 5 },
      { text: "Drink water", points: 4 },
      { text: "Fix pillow", points: 3 },
    ],
  },
  {
    Question: "Name something you wouldn't want to find on your bed",
    Answer: [
      { text: "Bugs/Animal", points: 10 },
      { text: "Food/crumbs", points: 9 },
      { text: "Dust", points: 8 },
      { text: "Wet spot", points: 7 },
      { text: "Stain", points: 6 },
      { text: "A stranger", points: 5 },
      { text: "Friend(s)", points: 4 },
      { text: "Your in-laws", points: 3 },
    ],
  },
  {
    Question: "What's the most annoying habit a roommate can have",
    Answer: [
      { text: "Being dirty", points: 10 },
      { text: "Snoring", points: 9 },
      { text: "Stealing", points: 8 },
      { text: "Noisy", points: 7 },
      { text: "Untidy", points: 6 },
      { text: "Using your stuff without asking", points: 5 },
      {
        text: "Always forgetting to return the money they owed from you",
        points: 4,
      },
      { text: "Being overly nosy", points: 3 },
    ],
  },
  {
    Question: "Name things that computer science students hardly do",
    Answer: [
      { text: "Getting a job💀", points: 10 },
      { text: "Socialize", points: 9 },
      { text: "Take a shower", points: 8 },
      { text: "Getting a partner", points: 7 },
      { text: "Sleep", points: 6 },
      { text: "Exercise", points: 5 },
      { text: "Debugging/fixing their code", points: 4 },
      { text: "Laundry", points: 3 },
    ],
  },
  {
    Question: "Name things that your roommate do while you're sleeping",
    Answer: [
      { text: "Also sleeping", points: 10 },
      { text: "Studying/doing assignments", points: 9 },
      { text: "Watching films/movies", points: 8 },
      { text: "Playing games", points: 7 },
      { text: "Taking a bath", points: 6 },
      { text: "Eating", points: 5 },
      { text: "Crying", points: 4 },
      { text: "Taking a photo of you", points: 3 },
    ],
  },
  {
    Question: "What’s something people often forget to pack for a trip​",
    Answer: [
      { text: "Underwear", points: 10 },
      { text: "Toothbrush", points: 9 },
      { text: "Phone charger", points: 8 },
      { text: "Medication", points: 7 },
      { text: "Travel documents", points: 6 },
      { text: "Sun screen", points: 5 },
      { text: "Shirt", points: 4 },
      { text: "Sandals", points: 3 },
    ],
  },
];
