export const finalQuestionData = [
  {
    Question: "Name something that starts with the word “chow”",
    Answer: [
      { text: "Chow-Mein", points: 10 },
      { text: "Chowder", points: 9 },
      { text: "Chow Time", points: 8 },
      { text: "Chow Down", points: 7 },
      { text: "Chow Hall", points: 6 },
      { text: "Chow Hound", points: 5 },
      { text: "Chow Chow", points: 4 },
      { text: "Chow Line", points: 3 },
    ],
  },
  {
    Question: "Fill in the blank: pack of _____",
    Answer: [
      { text: "Wolves", points: 10 },
      { text: "Gum", points: 9 },
      { text: "Cigs/smokes", points: 8 },
      { text: "Cards", points: 7 },
      { text: "Lies", points: 6 },
      { text: "abs", points: 5 },
      { text: "thieves", points: 4 },
      { text: "matches", points: 3 },
    ],
  },
  {
    Question: "Name Top 8 Most Listened Artist on Spotify in February 2025",
    Answer: [
      { text: "Bruno Mars", points: 10 },
      { text: "The Weeknd", points: 9 },
      { text: "Lady Gaga", points: 8 },
      { text: "Billie Eilish", points: 7 },
      { text: "Kendrick Lamar", points: 6 },
      { text: "Bad Bunny", points: 5 },
      { text: "ColdPlay", points: 4 },
      { text: "Rihanna", points: 3 },
    ],
  },
  {
    Question: "Whats the worse thing to say on a first date?",
    Answer: [
      { text: "So youre paying right?", points: 10 },
      { text: "My ex used to love this place", points: 9 },
      { text: "Oh i forgot my wallet", points: 8 },
      { text: "So how many kids do you want", points: 7 },
      { text: "nothing", points: 6 },
      { text: "you look ____ in person", points: 5 },
      {
        text: "My mom didn't want me to come on this date, but she won't be an issue anymore.",
        points: 4,
      },
      { text: "Marry me", points: 3 },
    ],
  },
  {
    Question: "Name a famous Hong Kong actor",
    Answer: [
      { text: "Bruce Lee", points: 10 },
      { text: "Jackie Chan", points: 9 },
      { text: "Chow Yun-Fat", points: 8 },
      { text: "Andy Lau", points: 7 },
      { text: "Jet Li", points: 6 },
      { text: "Leslie Cheung", points: 5 },
      { text: "Tony Leung Chiu-wai", points: 4 },
      { text: "Donnie Yen", points: 3 },
    ],
  },
  {
    Question: "What to do when you have a headache",
    Answer: [
      { text: "Go to the doctor", points: 10 },
      { text: "Go to amusement parks", points: 9 },
      { text: "Call a friend", points: 8 },
      { text: "Go shopping", points: 7 },
      { text: "Go to sleep", points: 6 },
      { text: "Eat medicine", points: 5 },
      { text: "Play games", points: 4 },
      { text: "Reels scrolling", points: 3 },
    ],
  },
  {
    Question: "What NOT to wear during a job interview",
    Answer: [
      { text: "Birthday suit (Nothing)", points: 10 },
      { text: "Shorts", points: 9 },
      { text: "Pajamas", points: 8 },
      { text: "Swimming suit", points: 7 },
      { text: "Torn clothes", points: 6 },
      { text: "hat", points: 5 },
      { text: "Dirty clothes", points: 4 },
      { text: "Flip flops", points: 3 },
    ],
  },
  {
    Question: "What do people usually eat in a buffet",
    Answer: [
      { text: "Bread", points: 10 },
      { text: "Seafood", points: 9 },
      { text: "Noodles", points: 8 },
      { text: "Ice Cream", points: 7 },
      { text: "Meat/Steak", points: 6 },
      { text: "Omelette egg", points: 5 },
      { text: "Cereal", points: 4 },
      { text: "Fruits", points: 3 },
    ],
  },
  {
    Question: "Name something that kids really like",
    Answer: [
      { text: "Toys", points: 10 },
      { text: "Candy", points: 9 },
      { text: "Vacation", points: 8 },
      { text: "Ice Cream", points: 7 },
      { text: "Video games", points: 6 },
      { text: "Running", points: 5 },
      { text: "Gadgets", points: 4 },
      { text: "Watching movies/videos", points: 3 },
    ],
  },
  {
    Question: "Largest cities in the world by population",
    Answer: [
      { text: "Tokyo", points: 10 },
      { text: "Delhi", points: 9 },
      { text: "Shanghai", points: 8 },
      { text: "Dhaka", points: 7 },
      { text: "Sao Paulo", points: 6 },
      { text: "Cairo", points: 5 },
      { text: "Mexico City", points: 4 },
      { text: "Beijing", points: 3 },
    ],
  },
  {
    Question: "Most populated countries",
    Answer: [
      { text: "India", points: 10 },
      { text: "China", points: 9 },
      { text: "Unites States", points: 8 },
      { text: "Indonesia", points: 7 },
      { text: "Pakistan", points: 6 },
      { text: "Nigeria", points: 5 },
      { text: "Brazil", points: 4 },
      { text: "Bangladesh", points: 3 },
    ],
  },
  {
    Question: "Famous Japanese Food",
    Answer: [
      { text: "Sushi", points: 10 },
      { text: "Ramen", points: 9 },
      { text: "Sashimi", points: 8 },
      { text: "Onigiri", points: 7 },
      { text: "Tempura", points: 6 },
      { text: "Takoyaki", points: 5 },
      { text: "Natto", points: 4 },
      { text: "Yakitori", points: 3 },
    ],
  },
  {
    Question: "World's Best Airlines of 2024",
    Answer: [
      { text: "Qatar Aiways", points: 10 },
      { text: "Singapore Airlines", points: 9 },
      { text: "Emirates", points: 8 },
      { text: "All Nippon Airways", points: 7 },
      { text: "Cathay Pacific", points: 6 },
      { text: "Japan Airlines", points: 5 },
      { text: "Turkish Airlines", points: 4 },
      { text: "Eva Air", points: 3 },
    ],
  },
  {
    Question: "Most Popular Pet",
    Answer: [
      { text: "Dog", points: 10 },
      { text: "Cat", points: 9 },
      { text: "Fish", points: 8 },
      { text: "Hamster", points: 7 },
      { text: "Rabbit", points: 6 },
      { text: "Bird", points: 5 },
      { text: "Reptile", points: 4 },
      { text: "Horse", points: 3 },
    ],
  },
  {
    Question: "What’s a common mode of transport in Hong Kong?",
    Answer: [
      { text: "MTR", points: 10 },
      { text: "Tram", points: 9 },
      { text: "Taxi", points: 8 },
      { text: "Bus", points: 7 },
      { text: "Ferry", points: 6 },
      { text: "Minibus", points: 5 },
      { text: "Bike", points: 4 },
      { text: "Walk", points: 3 },
    ],
  },
  {
    Question: "Name a popular local festival in Hong Kong.",
    Answer: [
      { text: "Mid-Autumn", points: 10 },
      { text: "Dragon Boat", points: 9 },
      { text: "Chinese New Year", points: 8 },
      { text: "Tin Hau", points: 7 },
      { text: "Cheung Chau Bun", points: 6 },
      { text: "Lantern Festival", points: 5 },
      { text: "Hungry Ghost", points: 4 },
      { text: "Christmas", points: 3 },
    ],
  },
  {
    Question: "What’s a must-visit place in Hong Kong?",
    Answer: [
      { text: "Victoria Peak", points: 10 },
      { text: "Tsim Sha Tsui", points: 9 },
      { text: "Disneyland", points: 8 },
      { text: "Lantau Island", points: 7 },
      { text: "Mong Kok", points: 6 },
      { text: "Temple Street", points: 5 },
      { text: "Ocean Park", points: 4 },
      { text: "Ngong Ping", points: 3 },
    ],
  },
  {
    Question: "Name a popular Hong Kong street food.",
    Answer: [
      { text: "Egg waffle", points: 10 },
      { text: "Stinky tofu", points: 9 },
      { text: "Fish balls", points: 8 },
      { text: "Pineapple bun", points: 7 },
      { text: "Cheung fun", points: 6 },
      { text: "Curry fish balls", points: 5 },
      { text: "Siu mai", points: 4 },
      { text: "Bubble tea", points: 3 },
    ],
  },
  {
    Question: "Name a kind of bear",
    Answer: [
      { text: "Polar bear", points: 10 },
      { text: "Brown bear", points: 9 },
      { text: "Grizzly Bear", points: 8 },
      { text: "Black bear", points: 7 },
      { text: "Panda", points: 6 },
      { text: "Moon bear", points: 5 },
      { text: "Sloth bear", points: 4 },
      { text: "Spectacled bear", points: 3 },
    ],
  },
  {
    Question: "What is something you blow?",
    Answer: [
      { text: "Baloon", points: 10 },
      { text: "Whistle", points: 9 },
      { text: "Horn/Party Horn", points: 8 },
      { text: "Candle", points: 7 },
      { text: "Kiss", points: 6 },
      { text: "Trumpet", points: 5 },
      { text: "Bubble", points: 4 },
      { text: "Flute", points: 3 },
    ],
  },
  {
    Question: 'Body part start with the letter "T"',
    Answer: [
      { text: "Tendon", points: 10 },
      { text: "Teeth", points: 9 },
      { text: "Thigh", points: 8 },
      { text: "Toes", points: 7 },
      { text: "Tongue", points: 6 },
      { text: "Tailbone", points: 5 },
      { text: "Throat", points: 4 },
      { text: "Thumb", points: 3 },
    ],
  },
  {
    Question:
      "Name something a husband might find all over the bed that makes him suspect his wife is having an affair with a baker",
    Answer: [
      { text: "Dough", points: 10 },
      { text: "Flour", points: 9 },
      { text: "Icing/Frosting", points: 8 },
      { text: "Sugar", points: 7 },
      { text: "Yeast", points: 6 },
      { text: "Egg", points: 5 },
      { text: "Baked goods/crumbs", points: 4 },
      { text: "Chocolate", points: 3 },
    ],
  },
  {
    Question: "Name a word that rhymes with “election.”",
    Answer: [
      { text: "Selection", points: 10 },
      { text: "Erection", points: 9 },
      { text: "Perfection", points: 8 },
      { text: "Detection", points: 7 },
      { text: "Protection", points: 6 },
      { text: "Collection", points: 5 },
      { text: "Rejection", points: 4 },
      { text: "Section", points: 3 },
    ],
  },
];
